### ISSUE TITLE
Password Confirmation from documentation and the actual code does not match 

### ISSUE THREAD

**Issue by danieltejano** [axe-api/validator#47]
Hi amazing package by the way really appreciate it.

I just wanted to notify that the confirmed rule format from the documentation still uses the {field}_confirmation format but when reviewing the code it uses the {field}_confirmed. Which confused me for a while when using the package. 

Keep the solid work up 👌.

**Comment by ozziest** [comment]
Hi @danieltejano!

Thank you very much for the feedback. ❤️ I've fixed the documentation. 🚀
